# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186cc9671dfa8cf6749ba3b42250228526de03c610161b1bf2cbc2fc983514e33735538d1ffa2221419c76ae23603f7bd2040decd3de6e9b4d377be6db73b049

test:
  secret_key_base: a6790b6ac41fc3ea49883bf019135d75a52a6a4e073fd18509eba9619fab4ccd636c9d62c77049541ce9959a1e35331d6b82aec370bc8e2cdd9bf60b38e17826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
